### ISSUE TITLE
Not install in Lazaruz 1.4.0 + FPC 2.6.4 + GR32 1.9.1 Fixes

### ISSUE THREAD

**Issue by clondono92150430** [CWBudde/Pascal-HTML5-Canvas#1]
It require GR32_Path and it not implemented in last version on GR32

And GR32 1.9.0 not complite, this is the error
GR32.pas(338,32) Error: No matching implementation for interface method "IUnknown.QueryInterface(constref TGuid,out <Formal type>):LongInt; StdCall;" found

**Comment by CWBudde** [comment]
Actually the trunk version of GR32 is needed (upcoming v2.0). It was supposed to be ready soon, but now there is no official release near due to lack of development.
